apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
data:
  IMAGE_URL: "/image_url"
  DBHOST: "e-mysql"
  DBPORT: "3306"
  GROUP_NAME: "GROUP07"
  IMAGE_S3: "https://finalproject-group7.s3.amazonaws.com/"
  image : "https://finalproject-group7.s3.amazonaws.com/cover.jpg"
  