apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-container
          image: 060735095223.dkr.ecr.us-east-1.amazonaws.com/finalproject-mysql:v1.0  # Updated MySQL image
          volumeMounts:
            - name: mysql-volume
              mountPath: /var/lib/mysql  # Mount path inside the container
      volumes:
        - name: mysql-volume
          persistentVolumeClaim:
            claimName: mysql-pvc  # Name of the existing PVC
