# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mysql-pvc
#   labels:
#     name: mysql-pvc
# spec:
#   storageClassName: gp2
#   resources:
#     requests:
#       storage: 2Gi
#   accessModes:
#     - ReadWriteOnce

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: mysql  # Example label indicating the app this PVC is associated with
spec:
  #storageClassName: gp2
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce

      
