apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: '060735095223.dkr.ecr.us-east-1.amazonaws.com/finalproject-mysql:v1.0'
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: db123
        ports:
          - containerPort: 3306
            protocol: TCP
        volumeMounts:
          - name: mysql-data
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  storageClassName: gp2  # Replace with your storage class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Adjust size as needed